spring:
    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://129.254.174.119:3306/etri
        username: root
        password: 1234
        hikari:
            idle-timeout: 300
            max-lifetime: 300
            maximum-pool-size: 4