spring:
    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/etri
        username: root
        password: 1234
        hikari:
            idle-timeout: 300
            max-lifetime: 300